<a href="https://colab.research.google.com/github/Charlene958/Data-201_Charlene/blob/main/Assignment2_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Loading the Dataset

In [3]:
import pandas as pd

df = pd.read_csv("housing (4).csv")
df.head()

   listing_id    price         size  bedrooms neighborhood          type
0      100001  1500000  1280.741760       1.0       Suburb     Townhouse
1      100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2      100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3      100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4      100005  1500000  1243.751760       1.0     Downtown   MultiFamily

##PART A — Method Chaining

In [4]:
summary = (
    df[(df["price"] > 250000) & (df["size"] > 1000)]
    .assign(price_per_sqft=lambda x: x["price"] / x["size"])
    .groupby("neighborhood")
    .agg(
        mean_price_per_sqft=("price_per_sqft", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        count_homes=("price_per_sqft", "count")
    )
    .sort_values(by="mean_price_per_sqft", ascending=False)
)

summary

              mean_price_per_sqft  median_price_per_sqft  count_homes
neighborhood
Downtown               977.820905            1001.557049           99
Midtown                921.141446             901.992377           92
Suburb                 861.917078             836.878644          157
Uptown                 860.935608             843.653468           99
Waterfront             849.508891             792.663291           48

##PART B — dplyr Version

In [6]:
summary_dplyr_equivalent = (
    df[(df["price"] > 250000) & (df["size"] > 1000)]
    .assign(price_per_sqft=lambda x: x["price"] / x["size"])
    .groupby("neighborhood")
    .agg(
        mean_price_per_sqft=("price_per_sqft", "mean"),
        median_price_per_sqft=("price_per_sqft", "median"),
        count_homes=("price_per_sqft", "count")
    )
    .sort_values(by="mean_price_per_sqft", ascending=False)
)

summary_dplyr_equivalent

              mean_price_per_sqft  median_price_per_sqft  count_homes
neighborhood
Downtown               977.820905            1001.557049           99
Midtown                921.141446             901.992377           92
Suburb                 861.917078             836.878644          157
Uptown                 860.935608             843.653468           99
Waterfront             849.508891             792.663291           48

##Reflection

I find pandas method chaining slightly more complex than dplyr pipelines because the syntax requires more attention to detail. However, both approaches follow a similar structure where data is filtered, transformed, grouped, and summarized step by step. The similarity is that both use a pipeline approach to make transformations readable. The difference is that dplyr feels more intuitive, while pandas requires more explicit syntax.

##PART C

In [7]:
df[(df["price"] > 250000) & (df["size"] > 1000)]

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

##Explanation

The error occurs because each condition must be wrapped in parentheses when using the & operator in pandas. Without parentheses, Python cannot correctly evaluate the boolean expressions due to operator precedence.

##Using .query()

In [8]:
df.query("price > 250000 and size > 1000")

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

##PART D

1. Each condition must be wrapped in parentheses because the & operator has higher precedence, and without parentheses, pandas cannot correctly evaluate the conditions.

2. Method chaining makes code cleaner and easier to read because all transformations are done in one continuous flow instead of creating multiple temporary DataFrames.

3. In ("price", "mean"), "price" is the column being used, and "mean" is the aggregation function applied to that column.

4. When using groupby("neighborhood"), pandas places neighborhood as the index because it becomes the grouping variable for the summarized output.

##OPTIONAL (Extra Practice)

In [9]:
df.groupby("type").agg(
    mean_price=("price", "mean"),
    median_price=("price", "median"),
    count_listings=("price", "count")
)

              mean_price  median_price  count_listings
type
Condo          1500000.0     1500000.0             183
MultiFamily    1500000.0     1500000.0              63
SingleFamily   1500000.0     1500000.0             235
Townhouse      1500000.0     1500000.0             119